name: Deploy manually

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/cache@v3
        id: client-pnpm-cache
        with:
          path: "node_modules"
          key: client-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6
      - name: install
        run: |
          pnpm install
      - name: build
        run: |
          pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist